version: "3.7"
services:
  street-comics-api:
    build:
      dockerfile: ./street-comics-api/Dockerfile
      context: .
    command: bundle exec puma -C config/puma.rb
    working_dir: /opt/app
    volumes:
      - ./street-comics-api:/opt/app
      - street-comics-api-bundle_path:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - ./street-comics-api/.env

  street-comics-frontend:
    image: node:14.17.4
    command: npm run start
    working_dir: /opt/app
    volumes:
      - ./street-comics-frontend:/opt/app
      - street-comics-frontend-node_modules:/opt/app/node_modules
    links:
      - street-comics-api
    ports:
      - "4000:3000"

volumes:
  street-comics-api-bundle_path:
  street-comics-frontend-node_modules:
