[build]
  command = "npm run build"
  base = "street-comics-frontend"
  publish = "build"

## Redirect API requests to the API server
[[redirects]]
  from = "/api/*"
  to = "https://street-comics-api.herokuapp.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

## Redirect anything else to the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
