FROM ruby:2.7.2
RUN gem install rails bundler

ENV RAILS_ENV production
ENV INSTALL_PATH /opt/app

RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

COPY . .

RUN bundle install

CMD bundle exec puma -C config/puma.rb