name: street-comics-frontend-ci
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./street-comics-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.4"

      - name: Run npm install
        run: npm install
        working-directory: ${{env.WORKING_DIR}}

      - name: Run tests
        run: npm test
        working-directory: ${{env.WORKING_DIR}}
